import type { TemplateConfig, PropertyData } from '../types';

export const TEMPLATE_REGISTRY: TemplateConfig[] = [
  {
    id: 'classic',
    name: '經典版',
    tier: 'free',
    canvasSize: { width: 1000, height: 1000 },
    backgroundColor: '#ffffff',
    elements: [
      {
        kind: 'property-image',
        id: 'prop-img',
        zIndex: 1,
        x: 0,
        y: 0,
        width: 1000,
        height: 660,
      },
      {
        kind: 'shape',
        id: 'info-bg',
        zIndex: 2,
        shapeType: 'rect',
        x: 0,
        y: 660,
        width: 1000,
        height: 340,
        fillColor: '#ffffff',
      },
      {
        kind: 'text-field',
        id: 'title',
        zIndex: 5,
        fieldKey: 'title',
        x: 40,
        y: 715,
        font: 'bold 34px Noto Serif TC',
        color: '#1f2937',
      },
      {
        kind: 'text-field',
        id: 'price',
        zIndex: 5,
        fieldKey: 'price',
        x: 40,
        y: 758,
        font: 'bold 34px Noto Serif TC',
        color: '#dc2626',
      },
      {
        kind: 'static-text',
        id: 'separator',
        zIndex: 5,
        value: '|',
        x: 210,
        y: 758,
        font: '30px Noto Serif TC',
        color: '#d1d5db',
      },
      {
        kind: 'text-field',
        id: 'area',
        zIndex: 5,
        fieldKey: 'area',
        x: 240,
        y: 758,
        font: '30px Noto Serif TC',
        color: '#6b7280',
      },
      {
        kind: 'text-field',
        id: 'description',
        zIndex: 5,
        fieldKey: 'description',
        x: 40,
        y: 800,
        font: '22px Noto Serif TC',
        color: '#4b5563',
        maxWidth: 920,
        lineHeight: 30,
      },
      {
        kind: 'shape',
        id: 'divider',
        zIndex: 5,
        shapeType: 'line',
        x: 40,
        y: 835,
        width: 920,
        height: 1,
        strokeColor: '#e5e7eb',
        lineWidth: 1,
      },
      {
        kind: 'avatar-image',
        id: 'avatar',
        zIndex: 4,
        x: 40,
        y: 850,
        width: 130,
        height: 130,
        shape: 'circle',
        borderColor: '#e5e7eb',
        borderWidth: 3,
      },
      {
        kind: 'text-field',
        id: 'agentName',
        zIndex: 5,
        fieldKey: 'agentName',
        x: 195,
        y: 920,
        font: 'bold 50px Noto Serif TC',
        color: '#1f2937',
      },
      {
        kind: 'text-field',
        id: 'companyName',
        zIndex: 5,
        fieldKey: 'companyName',
        x: 195,
        y: 960,
        font: '26px Noto Serif TC',
        color: '#6b7280',
      },
      {
        kind: 'static-text',
        id: 'phone-icon',
        zIndex: 5,
        value: '📞',
        x: 560,
        y: 920,
        font: '24px Noto Serif TC',
        color: '#374151',
      },
      {
        kind: 'text-field',
        id: 'phone',
        zIndex: 5,
        fieldKey: 'phone',
        x: 600,
        y: 920,
        font: '24px Noto Serif TC',
        color: '#374151',
      },
      {
        kind: 'static-text',
        id: 'line-icon',
        zIndex: 5,
        value: '💬LINE:',
        x: 560,
        y: 960,
        font: '24px Noto Serif TC',
        color: '#374151',
      },
      {
        kind: 'text-field',
        id: 'lineId',
        zIndex: 5,
        fieldKey: 'lineId',
        x: 672,
        y: 960,
        font: '24px Noto Serif TC',
        color: '#374151',
      },
    ],
  },
  {
    id: 'modern',
    name: '現代版',
    tier: 'free',
    canvasSize: { width: 1000, height: 1000 },
    backgroundColor: '#1a1a1a',
    elements: [
      {
        kind: 'property-image',
        id: 'prop-img',
        zIndex: 1,
        x: 30,
        y: 30,
        width: 940,
        height: 610,
      },
      {
        kind: 'text-field',
        id: 'title',
        zIndex: 5,
        fieldKey: 'title',
        x: 40,
        y: 690,
        font: 'bold 32px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'text-field',
        id: 'price',
        zIndex: 5,
        fieldKey: 'price',
        x: 40,
        y: 735,
        font: 'bold 34px Noto Serif TC',
        color: '#fbbf24',
      },
      {
        kind: 'static-text',
        id: 'separator',
        zIndex: 5,
        value: '|',
        x: 210,
        y: 735,
        font: '30px Noto Serif TC',
        color: 'rgba(255,255,255,0.3)',
      },
      {
        kind: 'text-field',
        id: 'area',
        zIndex: 5,
        fieldKey: 'area',
        x: 240,
        y: 735,
        font: '30px Noto Serif TC',
        color: '#9ca3af',
      },
      {
        kind: 'text-field',
        id: 'description',
        zIndex: 5,
        fieldKey: 'description',
        x: 40,
        y: 778,
        font: '20px Noto Serif TC',
        color: '#9ca3af',
        maxWidth: 920,
        lineHeight: 30,
      },
      {
        kind: 'shape',
        id: 'divider',
        zIndex: 5,
        shapeType: 'line',
        x: 40,
        y: 835,
        width: 920,
        height: 1,
        strokeColor: 'rgba(255,255,255,0.15)',
        lineWidth: 1,
      },
      {
        kind: 'avatar-image',
        id: 'avatar',
        zIndex: 4,
        x: 40,
        y: 850,
        width: 130,
        height: 130,
        shape: 'circle',
        borderColor: '#ffffff',
        borderWidth: 3,
      },
      {
        kind: 'text-field',
        id: 'agentName',
        zIndex: 5,
        fieldKey: 'agentName',
        x: 195,
        y: 920,
        font: 'bold 50px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'text-field',
        id: 'companyName',
        zIndex: 5,
        fieldKey: 'companyName',
        x: 195,
        y: 960,
        font: '26px Noto Serif TC',
        color: '#9ca3af',
      },
      {
        kind: 'static-text',
        id: 'phone-icon',
        zIndex: 5,
        value: '📞',
        x: 560,
        y: 920,
        font: '22px Noto Serif TC',
        color: '#fbbf24',
      },
      {
        kind: 'text-field',
        id: 'phone',
        zIndex: 5,
        fieldKey: 'phone',
        x: 598,
        y: 920,
        font: '22px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'static-text',
        id: 'line-icon',
        zIndex: 5,
        value: '💬LINE:',
        x: 560,
        y: 960,
        font: '22px Noto Serif TC',
        color: '#fbbf24',
      },
      {
        kind: 'text-field',
        id: 'lineId',
        zIndex: 5,
        fieldKey: 'lineId',
        x: 658,
        y: 960,
        font: '22px Noto Serif TC',
        color: '#ffffff',
      },
    ],
  },
  {
    id: 'luxury',
    name: '奢華版',
    tier: 'pro',
    canvasSize: { width: 1000, height: 1000 },
    backgroundColor: '#000000',
    elements: [
      {
        kind: 'property-image',
        id: 'prop-img',
        zIndex: 1,
        x: 0,
        y: 0,
        width: 1000,
        height: 1000,
      },
      {
        kind: 'shape',
        id: 'overlay',
        zIndex: 2,
        shapeType: 'rect',
        x: 0,
        y: 700,
        width: 1000,
        height: 300,
        fillColor: 'rgba(0,0,0,0.80)',
      },
      {
        kind: 'text-field',
        id: 'title',
        zIndex: 5,
        fieldKey: 'title',
        x: 40,
        y: 745,
        font: 'bold 36px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'text-field',
        id: 'price',
        zIndex: 5,
        fieldKey: 'price',
        x: 40,
        y: 792,
        font: 'bold 38px Noto Serif TC',
        color: '#D4AF37',
      },
      {
        kind: 'static-text',
        id: 'separator',
        zIndex: 5,
        value: '|',
        x: 230,
        y: 792,
        font: '34px Noto Serif TC',
        color: 'rgba(255,255,255,0.3)',
      },
      {
        kind: 'text-field',
        id: 'area',
        zIndex: 5,
        fieldKey: 'area',
        x: 260,
        y: 792,
        font: '32px Noto Serif TC',
        color: '#e5e7eb',
      },
      {
        kind: 'text-field',
        id: 'description',
        zIndex: 5,
        fieldKey: 'description',
        x: 40,
        y: 838,
        font: '20px Noto Serif TC',
        color: '#d1d5db',
        maxWidth: 920,
        lineHeight: 30,
      },
      {
        kind: 'shape',
        id: 'divider',
        zIndex: 5,
        shapeType: 'line',
        x: 40,
        y: 880,
        width: 920,
        height: 1,
        strokeColor: 'rgba(212,175,55,0.4)',
        lineWidth: 1,
      },
      {
        kind: 'avatar-image',
        id: 'avatar',
        zIndex: 4,
        x: 40,
        y: 893,
        width: 95,
        height: 95,
        shape: 'circle',
        borderColor: '#D4AF37',
        borderWidth: 3,
      },
      {
        kind: 'text-field',
        id: 'agentName',
        zIndex: 5,
        fieldKey: 'agentName',
        x: 155,
        y: 928,
        font: 'bold 32px Noto Serif TC',
        color: '#D4AF37',
      },
      {
        kind: 'text-field',
        id: 'companyName',
        zIndex: 5,
        fieldKey: 'companyName',
        x: 155,
        y: 962,
        font: '18px Noto Serif TC',
        color: '#f3f4f6',
      },
      {
        kind: 'static-text',
        id: 'phone-icon',
        zIndex: 5,
        value: '📞',
        x: 560,
        y: 928,
        font: '22px Noto Serif TC',
        color: '#D4AF37',
      },
      {
        kind: 'text-field',
        id: 'phone',
        zIndex: 5,
        fieldKey: 'phone',
        x: 598,
        y: 928,
        font: '22px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'static-text',
        id: 'line-icon',
        zIndex: 5,
        value: '💬LINE:',
        x: 560,
        y: 962,
        font: '22px Noto Serif TC',
        color: '#D4AF37',
      },
      {
        kind: 'text-field',
        id: 'lineId',
        zIndex: 5,
        fieldKey: 'lineId',
        x: 658,
        y: 962,
        font: '22px Noto Serif TC',
        color: '#ffffff',
      },
    ],
  },
  {
    id: 'sold',
    name: '賀成交',
    tier: 'pro',
    canvasSize: { width: 1000, height: 1000 },
    backgroundColor: '#f5f0eb',
    elements: [
      {
        kind: 'overlay-image',
        id: 'bg',
        zIndex: 1,
        assetPath: '/templates/template_luxury.png',
        x: 0,
        y: 0,
        width: 1000,
        height: 1000,
      },
      {
        kind: 'property-image',
        id: 'prop-img',
        zIndex: 2,
        x: 198,
        y: 328,
        width: 602,
        height: 384,
      },
      {
        kind: 'text-field',
        id: 'title',
        zIndex: 5,
        fieldKey: 'title',
        x: 500,
        y: 196,
        font: '28px Noto Serif TC',
        color: '#ffffff',
        align: 'center',
      },
      {
        kind: 'avatar-image',
        id: 'avatar',
        zIndex: 5,
        x: 129,
        y: 790,
        width: 184,
        height: 177,
        shape: 'circle',
        borderColor: '#D4AF37',
        borderWidth: 0,
      },
      {
        kind: 'text-field',
        id: 'agentName',
        zIndex: 6,
        fieldKey: 'agentName',
        x: 340,
        y: 880,
        font: 'bold 44px Noto Serif TC',
        color: '#D4AF37',
      },
      {
        kind: 'text-field',
        id: 'companyName',
        zIndex: 6,
        fieldKey: 'companyName',
        x: 340,
        y: 923,
        font: '22px Noto Serif TC',
        color: '#e5e7eb',
      },
      {
        kind: 'static-text',
        id: 'phone-icon',
        zIndex: 6,
        value: '📞',
        x: 340,
        y: 963,
        font: '22px Noto Serif TC',
        color: '#D4AF37',
      },
      {
        kind: 'text-field',
        id: 'phone',
        zIndex: 6,
        fieldKey: 'phone',
        x: 378,
        y: 963,
        font: '22px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'static-text',
        id: 'line-icon',
        zIndex: 6,
        value: '💬LINE:',
        x: 570,
        y: 963,
        font: '22px Noto Serif TC',
        color: '#D4AF37',
      },
      {
        kind: 'text-field',
        id: 'lineId',
        zIndex: 6,
        fieldKey: 'lineId',
        x: 668,
        y: 963,
        font: '22px Noto Serif TC',
        color: '#ffffff',
      },
    ],
  },
  {
    id: 'sold-red',
    name: '賀成交（喜氣版）',
    tier: 'pro',
    canvasSize: { width: 1000, height: 1000 },
    backgroundColor: '#8B0000',
    elements: [
      {
        kind: 'overlay-image',
        id: 'bg',
        zIndex: 1,
        assetPath: '/templates/template_sold_red.png',
        x: 0,
        y: 0,
        width: 1000,
        height: 1000,
      },
      {
        kind: 'property-image',
        id: 'prop-img',
        zIndex: 2,
        x: 152,
        y: 333,
        width: 692,
        height: 451,
      },
      {
        kind: 'avatar-image',
        id: 'avatar',
        zIndex: 5,
        x: 38,
        y: 760,
        width: 281,
        height: 281,
        shape: 'circle',
        borderColor: '#D4AF37',
        borderWidth: 0,
      },
      {
        kind: 'text-field',
        id: 'agentName',
        zIndex: 6,
        fieldKey: 'agentName',
        x: 368,
        y: 915,
        font: 'bold 48px Noto Serif TC',
        color: '#8B0000',
      },
      {
        kind: 'text-field',
        id: 'companyName',
        zIndex: 6,
        fieldKey: 'companyName',
        x: 368,
        y: 950,
        font: '22px Noto Serif TC',
        color: '#5a3a00',
      },
      {
        kind: 'static-text',
        id: 'phone-icon',
        zIndex: 6,
        value: '📞',
        x: 368,
        y: 980,
        font: '20px Noto Serif TC',
        color: '#8B0000',
      },
      {
        kind: 'text-field',
        id: 'phone',
        zIndex: 6,
        fieldKey: 'phone',
        x: 400,
        y: 980,
        font: '20px Noto Serif TC',
        color: '#5a3a00',
      },
      {
        kind: 'static-text',
        id: 'line-icon',
        zIndex: 6,
        value: '💬LINE:',
        x: 580,
        y: 980,
        font: '20px Noto Serif TC',
        color: '#8B0000',
      },
      {
        kind: 'text-field',
        id: 'lineId',
        zIndex: 6,
        fieldKey: 'lineId',
        x: 658,
        y: 980,
        font: '20px Noto Serif TC',
        color: '#5a3a00',
      },
    ],
  },
  {
    id: 'sold-crazy',
    name: '霸氣版',
    tier: 'pro',
    canvasSize: { width: 1000, height: 1000 },
    backgroundColor: '#FFD700',
    elements: [
      {
        kind: 'overlay-image',
        id: 'bg',
        zIndex: 1,
        assetPath: '/templates/template_sold_crazy.png',
        x: 0,
        y: 0,
        width: 1000,
        height: 1000,
      },
      {
        kind: 'property-image',
        id: 'prop-img',
        zIndex: 2,
        x: 50,
        y: 317,
        width: 901,
        height: 458,
      },
      {
        kind: 'text-field',
        id: 'title',
        zIndex: 6,
        fieldKey: 'title',
        x: 504,
        y: 247,
        font: 'bold 76px Noto Serif TC',
        color: '#ffffff',
        align: 'center',
      },
      {
        kind: 'avatar-image',
        id: 'avatar',
        zIndex: 5,
        x: 78,
        y: 807,
        width: 137,
        height: 139,
        shape: 'circle',
        borderColor: '#FFD700',
        borderWidth: 0,
      },
      {
        kind: 'text-field',
        id: 'agentName',
        zIndex: 6,
        fieldKey: 'agentName',
        x: 246,
        y: 905,
        font: 'bold 70px Noto Serif TC',
        color: '#1a1a1a',
      },
      {
        kind: 'text-field',
        id: 'companyName',
        zIndex: 6,
        fieldKey: 'companyName',
        x: 520,
        y: 850,
        font: '20px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'static-text',
        id: 'phone-icon',
        zIndex: 6,
        value: '📞',
        x: 520,
        y: 888,
        font: '22px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'text-field',
        id: 'phone',
        zIndex: 6,
        fieldKey: 'phone',
        x: 555,
        y: 888,
        font: 'bold 22px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'static-text',
        id: 'line-icon',
        zIndex: 6,
        value: '💬LINE:',
        x: 520,
        y: 925,
        font: '20px Noto Serif TC',
        color: '#ffffff',
      },
      {
        kind: 'text-field',
        id: 'lineId',
        zIndex: 6,
        fieldKey: 'lineId',
        x: 600,
        y: 925,
        font: '20px Noto Serif TC',
        color: '#ffffff',
      },
    ],
  },
];

export const DEFAULT_PROPERTY_DATA: PropertyData = {
  title: '捷運站旁5分鐘',
  price: '3,800萬',
  area: '45坪',
  layout: '3房2廳2衛',
  description: '近101大樓，交通便利，採光極佳，全新裝潢',
  phone: '0912-345-678',
  lineId: '@houseagent',
  agentName: '林可愛',
  companyName: '可愛可愛房地產公司',
};
